@startuml

abstract class DBConn
class UserAuthCtrl
class PostCtrl
class StatsCtrl
class ConsoleUI

DBConn <|-- UserAuthCtrl
DBConn <|-- StatsCtrl
DBConn <|-- PostCtrl
UserAuthCtrl"authCtrl: 1"<--ConsoleUI
PostCtrl"postCtrl: 1" <--ConsoleUI
StatsCtrl"statsCtrl: 1"<--ConsoleUI



abstract class DBConn {
#Connection conn;
#connect()
}

class UserAuthCtrl {
+login(String, String)
}

class StatsCtrl {
+verifyInstructor(String)
-verifyUserInCourse(String, String)
-printStats(String)
+getUserStats(String, String)
}

class ConsoleUI {
UserAuthCtrl authCtrl;
PostCtrl postCtrl;
StatsCtrl statsCtrl;


}



@enduml
