@startuml
actor Student1
Student1 -> ConsoleUI: login()
ConsoleUI -> Student1: "Email: "
Student1 --> ConsoleUI: "OlaNordmann@gmail.com"
ConsoleUI -> Student1: "Passord: "
Student1 --> ConsoleUI: "bestePassord123"
ConsoleUI -> UserAuthCtrl: login(email, password)
UserAuthCtrl--> ConsoleUI: true
ConsoleUI --> Student1: "Successfully logged in!"
@enduml
