@startuml
actor Student1
Student1 -> ConsoleUI: searchPost()
ConsoleUI -> Student1: "Search after: "
Student1 --> ConsoleUI: "WAL"
ConsoleUI --> Student1: "Search results: "
ConsoleUI -> PostCtrl: searchPosts(courseCode, keyword)
PostCtrl --> ConsoleUI: List with the corresponding postNrs
ConsoleUI --> Student1: //Shows the list//
@enduml
