@startuml
Actor Instructor1
Instructor1 -> ConsoleUI: viewStats()
ConsoleUI -> StatsCtrl: getUserStats(email, course)
StatsCtrl -> StatsCtrl: verifyInstructor(email) && verifyUserInCourse(email, course)
StatsCtrl --> StatsCtrl: true
StatsCtrl -> StatsCtrl: printStats(course)
StatsCtrl --> ConsoleUI: //Statistics for the course//
ConsoleUI --> Instructor1: //Shows statistics for the course//
@enduml
