@startuml
actor Instructor1
Instructor1 -> piazzaForum.ConsoleUI: createAnswerOn()
piazzaForum.ConsoleUI -> Instructor1: "Select post: "
piazzaForum.ConsoleUI -> piazzaForum.PostCtrl: getPosts(courseCode)
piazzaForum.PostCtrl --> piazzaForum.ConsoleUI: Returns postNr, Title and Folder for each post
piazzaForum.ConsoleUI -> Instructor1: //Shows StartingPost options//
Instructor1 --> piazzaForum.ConsoleUI: "2" //(Input value for option: "Første tittel (Folder: Exam)"//
piazzaForum.ConsoleUI -> Instructor1: "Text: "
Instructor1 --> piazzaForum.ConsoleUI: "Dette er et svar"
piazzaForum.ConsoleUI -> piazzaForum.PostCtrl: createAnswerOn(answerOnPost, answerText, courseCode, userEmail)
piazzaForum.PostCtrl -> piazzaForum.PostCtrl: getUserType(userEmail)
piazzaForum.PostCtrl --> piazzaForum.PostCtrl: "Instructor"
piazzaForum.PostCtrl -> piazzaForum.PostCtrl: //Checks if answer from an instructor already exists//
piazzaForum.PostCtrl --> piazzaForum.PostCtrl: //false (answer doesn't exist)//
piazzaForum.PostCtrl -> piazzaForum.PostCtrl: createReplyPost(null, answerOnPost, "Answer", answerText, courseCode, userEmail )
piazzaForum.PostCtrl -> piazzaForum.PostCtrl: createPost(answerText, courseCode, userEmail, "ReplyPost")
piazzaForum.PostCtrl --> piazzaForum.PostCtrl: true
piazzaForum.PostCtrl --> piazzaForum.ConsoleUI: true
piazzaForum.ConsoleUI --> Instructor1: "New answer created!"
@enduml
